### ISSUE TITLE
Change repository name from "site-files" to "home"

### ISSUE THREAD

**Issue by bonniekim** [WebDevDivas/home#4]
This is to create a nicer url (http://webdevdivas.github.io/home/).

**Comment by bonniekim** [comment]
I have pushed this forward. Add comments if you have thoughts.

**Comment by madeleineadkins** [comment]
Agreed--much better URL. Thanks!

**Comment by bonniekim** [comment]
Great! Closing this issue now.

**Comment by bonniekim** [comment]
Renamed repository to `WebDevDivas.github.io` to follow better repository naming convention.

This simplifies our url to `webdevdivas.github.io` (without the `/home` added) because literally naming a repository `(username or org name).github.io` makes github pages not include the addition path.
